refactor: deprecate non uri connection
go-spatial/tegola pull request #986
Opened 2024-03-20 16:49 UTC by iwpnd

closes #979

2024-03-21 00:04 UTC, ARolek requested changes
Looks really good in here! I only have some minor comments inline, mainly around adding some documentation referencing the pgxpool.ParseConfig function which has additional connection string params that we have deprecated config support for, but are still supported in the connection string.

2024-03-21 00:04 UTC, ARolek commented on mvtprovider/postgis/README.md
> -- `max_connections` (int): [Optional] The max connections to maintain in the connection pool. Defaults to 100. 0 means no max.
We should add a reference around some of these pgx specific configs. It looks like the [`ParseConfig` ](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#ParseConfig) function for pgxpool supports the following additional query strings:

* pool_max_conns: integer greater than 0 
* pool_min_conns: integer 0 or greater 
* pool_max_conn_lifetime: duration string 
* pool_max_conn_idle_time: duration string 
* pool_health_check_period: duration string 
* pool_max_conn_lifetime_jitter: duration string

I think adding some notes to the README about how this package uses `pgx` under the hood with a link with to the ParseConfig function and indicating some of the available connection config query strings would be really helpful.

2024-03-21 19:37 UTC, gdey approved these changes
LGTM, when you have a chance can you rebase the commits into a single narrative.

2024-03-22 03:23 UTC, ARolek approved these changes
Looks clean! Thanks for tackling that. Please squash the commits into a single one and then we can land this PR and get v0.20.0 of tegola released!

2024-03-26 22:15 UTC, iwpnd commented
lets go @ARolek

2024-03-28 17:17 UTC, merged